### ISSUE TITLE
Question: Getting code changes

### ISSUE THREAD

**Issue by davidlee321** [TQRG/security-patches-dataset#1]
Hello. Appreciate the work that went into creating this sizeable dataset. Are there scripts/code for getting commits' code changes? Looks like `scripts/download.py` contains most of the logic needed and a little bit of modification should do the trick. 

Thanks @sofiaoreis

**Comment by sofiaoreis** [comment]
Hi @davidlee321,

Thanks for reaching out! The `scripts/download.py` will download the entire codebases for the different versions involved in the patch (vulnerable and fixed versions). If you're only looking for the diff information between both versions, it won't work for you. You may have to perform some changes to that script. 

I plan to add that feature in the future. But I'm currently integrating other datasets and extracting the cve-details data from 2020 and 2021. I will release more data very soon. 

Feel free to contribute to the repo with a PR, if you want to. I will list you as a contributor.

**Comment by davidlee321** [comment]
So I was looking for solutions and the github API might cut it for Github repositories. Example:

shell```
curl \
  -H "Accept: application/vnd.github.v3.diff" \
  https://api.github.com/repos/TQRG/security-patches-dataset/commits/6ee8095bb232d1e190bf453af09fc87cae558d02
```

**Comment by davidlee321** [comment]
My python solution:

```python

import requests
import time
import pandas as pd
import numpy as np

df = pd.read_csv('dataset/positive.csv')
df['diff'] = np.nan # create empty column to write code diffs to later.

token = 'ghpas1244y6u23c4*****************'
rate_limit_per_sec = 5000 / 60 / 60     # Github API's rate limit for basic (non-enterprise) users.
duration_per_request_minimum_s = (1.0 / rate_limit_per_sec) * 1.05      # additional 5% time leeway.
report_every = 100
errors = []

for i in range(len(df)):
    start = time.time()

    hash = df['sha'][i]
    project = df['project'][i]
    if 'github' not in project.lower():
        print(f'[WARN] {project} (row {i}) not on Github. Cannot use Github API. Skipped.')
        errors.append(f'row {i} not-github-project')
        continue #skip row
    split = project.split('/')
    owner, repo = split[-2], split[-1]
    query_url = f"https://api.github.com/repos/{owner}/{repo}/commits/{hash}"
    headers = {'Accept': 'application/vnd.github.v3.diff'}
    if token:
        headers['Authorization'] = f'token {token}'
    r = requests.get(query_url, headers=headers)
    if 200 == r.status_code:
        df['diff'][i] = r.text
        # print(r.text)
        # print('-' * 20)
    else:
        print(f'[WARN] GET request for {project} (row {i}) failed with status code {r.status_code}. Skipped.')
        errors.append(f'row {i} status-not-200')
        continue #skip row

    duration = time.time() - start
    if duration < duration_per_request_minimum_s:
        sleep_s = duration_per_request_minimum_s - duration
        time.sleep(sleep_s)

    if i % report_every == 0:
        print(f'[INFO] Done {i+1} rows.')

if errors:
    print('[WARN] ERRORS DETECTED. SEE VARIABLE `errors` FOR DETAILS.')
else:
    print('[INFO] No errors.')

df

```

**Comment by davidlee321** [comment]
no problem. thank you for building & curating this dataset. 

Regarding the challenge of saving a chain of commits, don't think I have an enlightened opinion. I agree with the ideas outlined. I think it's a good way forward for now. If users would like to obtain commits along the chain (I believe these are A, B, C in your comment), they might opt to use, say, github's API to manually grab them (like I did above).

After finding the proportion of samples that have this chain-of-commits situation, we will have a better idea of whether to deem this a special case or a common one. If common, contributors might like to consider providing these commits in the dataset. If this were to happen, to my knowledge, this would be one of the more complete & comprehensive security-related commit datasets publicly available.
