### ISSUE TITLE
Paper for Dataset

### ISSUE THREAD

**Issue by davidlee321** [TQRG/security-patches-dataset#2]
Would it be possible to make the paper for this dataset "A ground-truth dataset of real security patches" public? The openreview.net [link](https://openreview.net/pdf?id=Q0SbORK5zoN) has been down for some time. This is the link Google Scholar returns.

**Comment by sofiaoreis** [comment]
Hey, sure! I'll do that in the next 2/3 days. I'll ping you when it's done.

**Comment by sofiaoreis** [comment]
No worries! My plan was to make it available anyways. I'll extend the work soon. 

Paper is available here: https://arxiv.org/abs/2110.09635
