### ISSUE TITLE
Filter by language

### ISSUE THREAD

**Issue by fdebeyan** [TQRG/security-patches-dataset#8]
Thank you for providing this great vulnerability patches dataset.

Is it possible to filter patches by programming language? I see that some datasets include a language field while others don't.

**Comment by sofiaoreis** [comment]
Hi! 

Thanks for reaching out. I just noticed that the final dataset that merges all the sources was missing out from the repo. 

Here you can find the security patches dataset and negative/non-vulnerable data (extra patches): https://github.com/TQRG/security-patches-dataset/tree/main/dataset. There is a column called lang for language filtration.

The previous dataset is reported here: https://arxiv.org/abs/2110.09635.

I'm about to release a new version with a new schema. It will take me a while to document the new schema, though.
